// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFamilyMember = `-- name: AddFamilyMember :exec
INSERT INTO family_members (user_id, family_id, role) VALUES ($1, $2, $3)
`

type AddFamilyMemberParams struct {
	UserID   uuid.UUID `json:"userId"`
	FamilyID uuid.UUID `json:"familyId"`
	Role     string    `json:"role"`
}

func (q *Queries) AddFamilyMember(ctx context.Context, arg AddFamilyMemberParams) error {
	_, err := q.db.Exec(ctx, addFamilyMember, arg.UserID, arg.FamilyID, arg.Role)
	return err
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
DELETE FROM refresh_tokens
WHERE token_hash = $1 AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createFamily = `-- name: CreateFamily :one
INSERT INTO families (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateFamily(ctx context.Context, name string) (Family, error) {
	row := q.db.QueryRow(ctx, createFamily, name)
	var i Family
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (code, family_id, created_by, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateInviteParams struct {
	Code      string    `json:"code"`
	FamilyID  uuid.UUID `json:"familyId"`
	CreatedBy uuid.UUID `json:"createdBy"`
	ExpiresAt time.Time `json:"expiresAt"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.Code,
		arg.FamilyID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"userId"`
	TokenHash string    `json:"tokenHash"`
	ExpiresAt time.Time `json:"expiresAt"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, color)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, color, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
	Name         string `json:"name"`
	Color        string `json:"color"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Color,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFamily = `-- name: DeleteFamily :exec
DELETE FROM families WHERE id = $1
`

func (q *Queries) DeleteFamily(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFamily, id)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, tokenHash)
	return err
}

const deleteUserRefreshTokens = `-- name: DeleteUserRefreshTokens :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRefreshTokens, userID)
	return err
}

const getActiveInvite = `-- name: GetActiveInvite :one
SELECT code, family_id FROM invites
WHERE code = $1 AND used_at IS NULL AND expires_at > now()
`

type GetActiveInviteRow struct {
	Code     string    `json:"code"`
	FamilyID uuid.UUID `json:"familyId"`
}

func (q *Queries) GetActiveInvite(ctx context.Context, code string) (GetActiveInviteRow, error) {
	row := q.db.QueryRow(ctx, getActiveInvite, code)
	var i GetActiveInviteRow
	err := row.Scan(&i.Code, &i.FamilyID)
	return i, err
}

const getFamily = `-- name: GetFamily :one
SELECT id, name, created_at FROM families WHERE id = $1
`

func (q *Queries) GetFamily(ctx context.Context, id uuid.UUID) (Family, error) {
	row := q.db.QueryRow(ctx, getFamily, id)
	var i Family
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT user_id, family_id, role, joined_at FROM family_members WHERE user_id = $1
`

func (q *Queries) GetMembership(ctx context.Context, userID uuid.UUID) (FamilyMember, error) {
	row := q.db.QueryRow(ctx, getMembership, userID)
	var i FamilyMember
	err := row.Scan(
		&i.UserID,
		&i.FamilyID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, color, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, color, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listFamilyMembers = `-- name: ListFamilyMembers :many
SELECT u.id, u.name, u.color, u.email, fm.role, fm.joined_at
FROM family_members fm
JOIN users u ON u.id = fm.user_id
WHERE fm.family_id = $1
ORDER BY fm.joined_at, u.id
`

type ListFamilyMembersRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Color    string    `json:"color"`
	Email    string    `json:"email"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joinedAt"`
}

func (q *Queries) ListFamilyMembers(ctx context.Context, familyID uuid.UUID) ([]ListFamilyMembersRow, error) {
	rows, err := q.db.Query(ctx, listFamilyMembers, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFamilyMembersRow
	for rows.Next() {
		var i ListFamilyMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Email,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestMember = `-- name: OldestMember :one
SELECT user_id FROM family_members WHERE family_id = $1 ORDER BY joined_at, user_id LIMIT 1
`

func (q *Queries) OldestMember(ctx context.Context, familyID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, oldestMember, familyID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const removeFamilyMember = `-- name: RemoveFamilyMember :execrows
DELETE FROM family_members WHERE user_id = $1 AND family_id = $2
`

type RemoveFamilyMemberParams struct {
	UserID   uuid.UUID `json:"userId"`
	FamilyID uuid.UUID `json:"familyId"`
}

func (q *Queries) RemoveFamilyMember(ctx context.Context, arg RemoveFamilyMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFamilyMember, arg.UserID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMemberRole = `-- name: SetMemberRole :exec
UPDATE family_members SET role = $3 WHERE user_id = $1 AND family_id = $2
`

type SetMemberRoleParams struct {
	UserID   uuid.UUID `json:"userId"`
	FamilyID uuid.UUID `json:"familyId"`
	Role     string    `json:"role"`
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) error {
	_, err := q.db.Exec(ctx, setMemberRole, arg.UserID, arg.FamilyID, arg.Role)
	return err
}

const useInvite = `-- name: UseInvite :execrows
UPDATE invites SET used_at = now()
WHERE code = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) UseInvite(ctx context.Context, code string) (int64, error) {
	result, err := q.db.Exec(ctx, useInvite, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
