// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeCard = `-- name: CloseCard :execrows
UPDATE credit_cards SET status = 'closed' WHERE id = $1 AND family_id = $2 AND (scope = 'family' OR user_id = $3)
`

type CloseCardParams struct {
	ID       uuid.UUID `json:"id"`
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) CloseCard(ctx context.Context, arg CloseCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeCard, arg.ID, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closePayment = `-- name: ClosePayment :execrows
UPDATE recurring_payments SET status = 'closed' WHERE id = $1 AND family_id = $2 AND (scope = 'family' OR user_id = $3)
`

type ClosePaymentParams struct {
	ID       uuid.UUID `json:"id"`
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) ClosePayment(ctx context.Context, arg ClosePaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, closePayment, arg.ID, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCard = `-- name: CreateCard :one
INSERT INTO credit_cards (family_id, user_id, bank, amount_due, due_date, category_id, notify_days_before, scope, credit_limit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, family_id, user_id, bank, amount_due, due_date, category_id, notify_days_before, scope, status, credit_limit, created_at
`

type CreateCardParams struct {
	FamilyID         uuid.UUID `json:"familyId"`
	UserID           uuid.UUID `json:"userId"`
	Bank             string    `json:"bank"`
	AmountDue        int64     `json:"amountDue"`
	DueDate          time.Time `json:"dueDate"`
	CategoryID       string    `json:"categoryId"`
	NotifyDaysBefore int32     `json:"notifyDaysBefore"`
	Scope            string    `json:"scope"`
	CreditLimit      *int64    `json:"creditLimit"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.FamilyID,
		arg.UserID,
		arg.Bank,
		arg.AmountDue,
		arg.DueDate,
		arg.CategoryID,
		arg.NotifyDaysBefore,
		arg.Scope,
		arg.CreditLimit,
	)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Bank,
		&i.AmountDue,
		&i.DueDate,
		&i.CategoryID,
		&i.NotifyDaysBefore,
		&i.Scope,
		&i.Status,
		&i.CreditLimit,
		&i.CreatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, family_id, name, kind) VALUES ($1, $2, $3, $4) RETURNING id, name, kind
`

type CreateCategoryParams struct {
	ID       string      `json:"id"`
	FamilyID pgtype.UUID `json:"familyId"`
	Name     string      `json:"name"`
	Kind     string      `json:"kind"`
}

type CreateCategoryRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Kind string `json:"kind"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.FamilyID,
		arg.Name,
		arg.Kind,
	)
	var i CreateCategoryRow
	err := row.Scan(&i.ID, &i.Name, &i.Kind)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO savings_goals (family_id, user_id, name, target, saved, deadline, scope)
VALUES ($6, $7, $1, $2, $3, $4, $5)
RETURNING id, family_id, user_id, name, target, saved, deadline, scope
`

type CreateGoalParams struct {
	Name     string     `json:"name"`
	Target   *int64     `json:"target"`
	Saved    int64      `json:"saved"`
	Deadline *time.Time `json:"deadline"`
	Scope    string     `json:"scope"`
	FamilyID uuid.UUID  `json:"familyId"`
	UserID   uuid.UUID  `json:"userId"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.Name,
		arg.Target,
		arg.Saved,
		arg.Deadline,
		arg.Scope,
		arg.FamilyID,
		arg.UserID,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Name,
		&i.Target,
		&i.Saved,
		&i.Deadline,
		&i.Scope,
	)
	return i, err
}

const createLimit = `-- name: CreateLimit :one
INSERT INTO category_limits (family_id, user_id, category_id, limit_amount, scope)
VALUES ($4, $5, $1, $2, $3)
RETURNING id, family_id, user_id, category_id, limit_amount, scope
`

type CreateLimitParams struct {
	CategoryID  string    `json:"categoryId"`
	LimitAmount int64     `json:"limitAmount"`
	Scope       string    `json:"scope"`
	FamilyID    uuid.UUID `json:"familyId"`
	UserID      uuid.UUID `json:"userId"`
}

func (q *Queries) CreateLimit(ctx context.Context, arg CreateLimitParams) (CategoryLimit, error) {
	row := q.db.QueryRow(ctx, createLimit,
		arg.CategoryID,
		arg.LimitAmount,
		arg.Scope,
		arg.FamilyID,
		arg.UserID,
	)
	var i CategoryLimit
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.CategoryID,
		&i.LimitAmount,
		&i.Scope,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO recurring_payments (family_id, user_id, name, kind, amount, period, next_date, category_id, notify_days_before, scope, total_amount, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, family_id, user_id, name, kind, amount, period, next_date, category_id, notify_days_before, scope, status, total_amount, end_date, created_at
`

type CreatePaymentParams struct {
	FamilyID         uuid.UUID  `json:"familyId"`
	UserID           uuid.UUID  `json:"userId"`
	Name             string     `json:"name"`
	Kind             string     `json:"kind"`
	Amount           int64      `json:"amount"`
	Period           string     `json:"period"`
	NextDate         time.Time  `json:"nextDate"`
	CategoryID       string     `json:"categoryId"`
	NotifyDaysBefore int32      `json:"notifyDaysBefore"`
	Scope            string     `json:"scope"`
	TotalAmount      *int64     `json:"totalAmount"`
	EndDate          *time.Time `json:"endDate"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.FamilyID,
		arg.UserID,
		arg.Name,
		arg.Kind,
		arg.Amount,
		arg.Period,
		arg.NextDate,
		arg.CategoryID,
		arg.NotifyDaysBefore,
		arg.Scope,
		arg.TotalAmount,
		arg.EndDate,
	)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Amount,
		&i.Period,
		&i.NextDate,
		&i.CategoryID,
		&i.NotifyDaysBefore,
		&i.Scope,
		&i.Status,
		&i.TotalAmount,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (family_id, author_id, amount, date, category_id, type, scope, source)
VALUES ($7, $8, $1, $2, $3, $4, $5, $6)
RETURNING id, family_id, author_id, amount, date, category_id, type, scope, source, created_at, seller_inn, seller_name, receipt_key
`

type CreateTransactionParams struct {
	Amount     int64     `json:"amount"`
	Date       time.Time `json:"date"`
	CategoryID string    `json:"categoryId"`
	Type       string    `json:"type"`
	Scope      string    `json:"scope"`
	Source     string    `json:"source"`
	FamilyID   uuid.UUID `json:"familyId"`
	UserID     uuid.UUID `json:"userId"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Amount,
		arg.Date,
		arg.CategoryID,
		arg.Type,
		arg.Scope,
		arg.Source,
		arg.FamilyID,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AuthorID,
		&i.Amount,
		&i.Date,
		&i.CategoryID,
		&i.Type,
		&i.Scope,
		&i.Source,
		&i.CreatedAt,
		&i.SellerInn,
		&i.SellerName,
		&i.ReceiptKey,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :execrows
DELETE FROM savings_goals WHERE id = $1 AND family_id = $2 AND (scope = 'family' OR user_id = $3)
`

type DeleteGoalParams struct {
	ID       uuid.UUID `json:"id"`
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLimit = `-- name: DeleteLimit :execrows
DELETE FROM category_limits WHERE id = $1 AND family_id = $2 AND (scope = 'family' OR user_id = $3)
`

type DeleteLimitParams struct {
	ID       uuid.UUID `json:"id"`
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteLimit(ctx context.Context, arg DeleteLimitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLimit, arg.ID, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = $1 AND family_id = $2 AND (scope = 'family' OR author_id = $3)
`

type DeleteTransactionParams struct {
	ID       uuid.UUID `json:"id"`
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCardForUpdate = `-- name: GetCardForUpdate :one
SELECT id, family_id, user_id, bank, amount_due, due_date, category_id, notify_days_before, scope, status, credit_limit, created_at FROM credit_cards WHERE id = $1 AND family_id = $2 AND (scope = 'family' OR user_id = $3) FOR UPDATE
`

type GetCardForUpdateParams struct {
	ID       uuid.UUID `json:"id"`
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) GetCardForUpdate(ctx context.Context, arg GetCardForUpdateParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, getCardForUpdate, arg.ID, arg.FamilyID, arg.UserID)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Bank,
		&i.AmountDue,
		&i.DueDate,
		&i.CategoryID,
		&i.NotifyDaysBefore,
		&i.Scope,
		&i.Status,
		&i.CreditLimit,
		&i.CreatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, kind FROM categories WHERE id = $1 AND (family_id IS NULL OR family_id = $2)
`

type GetCategoryParams struct {
	ID       string      `json:"id"`
	FamilyID pgtype.UUID `json:"familyId"`
}

type GetCategoryRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Kind string `json:"kind"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.FamilyID)
	var i GetCategoryRow
	err := row.Scan(&i.ID, &i.Name, &i.Kind)
	return i, err
}

const getPaymentForUpdate = `-- name: GetPaymentForUpdate :one
SELECT id, family_id, user_id, name, kind, amount, period, next_date, category_id, notify_days_before, scope, status, total_amount, end_date, created_at FROM recurring_payments WHERE id = $1 AND family_id = $2 AND (scope = 'family' OR user_id = $3) FOR UPDATE
`

type GetPaymentForUpdateParams struct {
	ID       uuid.UUID `json:"id"`
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) GetPaymentForUpdate(ctx context.Context, arg GetPaymentForUpdateParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, getPaymentForUpdate, arg.ID, arg.FamilyID, arg.UserID)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Amount,
		&i.Period,
		&i.NextDate,
		&i.CategoryID,
		&i.NotifyDaysBefore,
		&i.Scope,
		&i.Status,
		&i.TotalAmount,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const listCards = `-- name: ListCards :many
SELECT id, family_id, user_id, bank, amount_due, due_date, category_id, notify_days_before, scope, status, credit_limit, created_at FROM credit_cards WHERE family_id = $1 AND (scope = 'family' OR user_id = $2) ORDER BY created_at
`

type ListCardsParams struct {
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) ListCards(ctx context.Context, arg ListCardsParams) ([]CreditCard, error) {
	rows, err := q.db.Query(ctx, listCards, arg.FamilyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditCard
	for rows.Next() {
		var i CreditCard
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.UserID,
			&i.Bank,
			&i.AmountDue,
			&i.DueDate,
			&i.CategoryID,
			&i.NotifyDaysBefore,
			&i.Scope,
			&i.Status,
			&i.CreditLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, kind FROM categories WHERE family_id IS NULL OR family_id = $1 ORDER BY family_id NULLS FIRST, name
`

type ListCategoriesRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Kind string `json:"kind"`
}

func (q *Queries) ListCategories(ctx context.Context, familyID pgtype.UUID) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, family_id, user_id, name, target, saved, deadline, scope FROM savings_goals WHERE family_id = $1 AND (scope = 'family' OR user_id = $2) ORDER BY deadline
`

type ListGoalsParams struct {
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) ListGoals(ctx context.Context, arg ListGoalsParams) ([]SavingsGoal, error) {
	rows, err := q.db.Query(ctx, listGoals, arg.FamilyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavingsGoal
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.UserID,
			&i.Name,
			&i.Target,
			&i.Saved,
			&i.Deadline,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLimits = `-- name: ListLimits :many
SELECT id, family_id, user_id, category_id, limit_amount, scope FROM category_limits WHERE family_id = $1 AND (scope = 'family' OR user_id = $2) ORDER BY category_id
`

type ListLimitsParams struct {
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) ListLimits(ctx context.Context, arg ListLimitsParams) ([]CategoryLimit, error) {
	rows, err := q.db.Query(ctx, listLimits, arg.FamilyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryLimit
	for rows.Next() {
		var i CategoryLimit
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.UserID,
			&i.CategoryID,
			&i.LimitAmount,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT id, family_id, user_id, name, kind, amount, period, next_date, category_id, notify_days_before, scope, status, total_amount, end_date, created_at FROM recurring_payments WHERE family_id = $1 AND (scope = 'family' OR user_id = $2) ORDER BY created_at
`

type ListPaymentsParams struct {
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]RecurringPayment, error) {
	rows, err := q.db.Query(ctx, listPayments, arg.FamilyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringPayment
	for rows.Next() {
		var i RecurringPayment
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.Amount,
			&i.Period,
			&i.NextDate,
			&i.CategoryID,
			&i.NotifyDaysBefore,
			&i.Scope,
			&i.Status,
			&i.TotalAmount,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, family_id, author_id, amount, date, category_id, type, scope, source, created_at, seller_inn, seller_name, receipt_key FROM transactions WHERE family_id = $1 AND (scope = 'family' OR author_id = $2) ORDER BY date DESC, created_at DESC
`

type ListTransactionsParams struct {
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.FamilyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AuthorID,
			&i.Amount,
			&i.Date,
			&i.CategoryID,
			&i.Type,
			&i.Scope,
			&i.Source,
			&i.CreatedAt,
			&i.SellerInn,
			&i.SellerName,
			&i.ReceiptKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCardDueDate = `-- name: SetCardDueDate :exec
UPDATE credit_cards SET due_date = $2 WHERE id = $1
`

type SetCardDueDateParams struct {
	ID      uuid.UUID `json:"id"`
	DueDate time.Time `json:"dueDate"`
}

func (q *Queries) SetCardDueDate(ctx context.Context, arg SetCardDueDateParams) error {
	_, err := q.db.Exec(ctx, setCardDueDate, arg.ID, arg.DueDate)
	return err
}

const setPaymentNextDate = `-- name: SetPaymentNextDate :exec
UPDATE recurring_payments SET next_date = $2 WHERE id = $1
`

type SetPaymentNextDateParams struct {
	ID       uuid.UUID `json:"id"`
	NextDate time.Time `json:"nextDate"`
}

func (q *Queries) SetPaymentNextDate(ctx context.Context, arg SetPaymentNextDateParams) error {
	_, err := q.db.Exec(ctx, setPaymentNextDate, arg.ID, arg.NextDate)
	return err
}

const topUpGoal = `-- name: TopUpGoal :one
UPDATE savings_goals SET saved = saved + $1
WHERE id = $2 AND family_id = $3 AND (scope = 'family' OR user_id = $4)
RETURNING id, family_id, user_id, name, target, saved, deadline, scope
`

type TopUpGoalParams struct {
	Amount   int64     `json:"amount"`
	ID       uuid.UUID `json:"id"`
	FamilyID uuid.UUID `json:"familyId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) TopUpGoal(ctx context.Context, arg TopUpGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, topUpGoal,
		arg.Amount,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Name,
		&i.Target,
		&i.Saved,
		&i.Deadline,
		&i.Scope,
	)
	return i, err
}

const updateCard = `-- name: UpdateCard :one
UPDATE credit_cards SET bank = $1, amount_due = $2, due_date = $3,
  category_id = $4, notify_days_before = $5, scope = $6,
  credit_limit = $7
WHERE id = $8 AND family_id = $9 AND (scope = 'family' OR user_id = $10) AND ($6::text = 'family' OR user_id = $10)
RETURNING id, family_id, user_id, bank, amount_due, due_date, category_id, notify_days_before, scope, status, credit_limit, created_at
`

type UpdateCardParams struct {
	Bank             string    `json:"bank"`
	AmountDue        int64     `json:"amountDue"`
	DueDate          time.Time `json:"dueDate"`
	CategoryID       string    `json:"categoryId"`
	NotifyDaysBefore int32     `json:"notifyDaysBefore"`
	Scope            string    `json:"scope"`
	CreditLimit      *int64    `json:"creditLimit"`
	ID               uuid.UUID `json:"id"`
	FamilyID         uuid.UUID `json:"familyId"`
	UserID           uuid.UUID `json:"userId"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.Bank,
		arg.AmountDue,
		arg.DueDate,
		arg.CategoryID,
		arg.NotifyDaysBefore,
		arg.Scope,
		arg.CreditLimit,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
	)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Bank,
		&i.AmountDue,
		&i.DueDate,
		&i.CategoryID,
		&i.NotifyDaysBefore,
		&i.Scope,
		&i.Status,
		&i.CreditLimit,
		&i.CreatedAt,
	)
	return i, err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE savings_goals SET name = $1, target = $2, saved = $3, deadline = $4, scope = $5
WHERE id = $6 AND family_id = $7 AND (scope = 'family' OR user_id = $8) AND ($5::text = 'family' OR user_id = $8)
RETURNING id, family_id, user_id, name, target, saved, deadline, scope
`

type UpdateGoalParams struct {
	Name     string     `json:"name"`
	Target   *int64     `json:"target"`
	Saved    int64      `json:"saved"`
	Deadline *time.Time `json:"deadline"`
	Scope    string     `json:"scope"`
	ID       uuid.UUID  `json:"id"`
	FamilyID uuid.UUID  `json:"familyId"`
	UserID   uuid.UUID  `json:"userId"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.Name,
		arg.Target,
		arg.Saved,
		arg.Deadline,
		arg.Scope,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Name,
		&i.Target,
		&i.Saved,
		&i.Deadline,
		&i.Scope,
	)
	return i, err
}

const updateLimit = `-- name: UpdateLimit :one
UPDATE category_limits SET category_id = $1, limit_amount = $2, scope = $3
WHERE id = $4 AND family_id = $5 AND (scope = 'family' OR user_id = $6) AND ($3::text = 'family' OR user_id = $6)
RETURNING id, family_id, user_id, category_id, limit_amount, scope
`

type UpdateLimitParams struct {
	CategoryID  string    `json:"categoryId"`
	LimitAmount int64     `json:"limitAmount"`
	Scope       string    `json:"scope"`
	ID          uuid.UUID `json:"id"`
	FamilyID    uuid.UUID `json:"familyId"`
	UserID      uuid.UUID `json:"userId"`
}

func (q *Queries) UpdateLimit(ctx context.Context, arg UpdateLimitParams) (CategoryLimit, error) {
	row := q.db.QueryRow(ctx, updateLimit,
		arg.CategoryID,
		arg.LimitAmount,
		arg.Scope,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
	)
	var i CategoryLimit
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.CategoryID,
		&i.LimitAmount,
		&i.Scope,
	)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE recurring_payments SET name = $1, kind = $2, amount = $3, period = $4,
  next_date = $5, category_id = $6, notify_days_before = $7,
  scope = $8, total_amount = $9, end_date = $10
WHERE id = $11 AND family_id = $12 AND (scope = 'family' OR user_id = $13) AND ($8::text = 'family' OR user_id = $13)
RETURNING id, family_id, user_id, name, kind, amount, period, next_date, category_id, notify_days_before, scope, status, total_amount, end_date, created_at
`

type UpdatePaymentParams struct {
	Name             string     `json:"name"`
	Kind             string     `json:"kind"`
	Amount           int64      `json:"amount"`
	Period           string     `json:"period"`
	NextDate         time.Time  `json:"nextDate"`
	CategoryID       string     `json:"categoryId"`
	NotifyDaysBefore int32      `json:"notifyDaysBefore"`
	Scope            string     `json:"scope"`
	TotalAmount      *int64     `json:"totalAmount"`
	EndDate          *time.Time `json:"endDate"`
	ID               uuid.UUID  `json:"id"`
	FamilyID         uuid.UUID  `json:"familyId"`
	UserID           uuid.UUID  `json:"userId"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, updatePayment,
		arg.Name,
		arg.Kind,
		arg.Amount,
		arg.Period,
		arg.NextDate,
		arg.CategoryID,
		arg.NotifyDaysBefore,
		arg.Scope,
		arg.TotalAmount,
		arg.EndDate,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
	)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Amount,
		&i.Period,
		&i.NextDate,
		&i.CategoryID,
		&i.NotifyDaysBefore,
		&i.Scope,
		&i.Status,
		&i.TotalAmount,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions SET amount = $1, date = $2, category_id = $3, type = $4, scope = $5
WHERE id = $6 AND family_id = $7 AND (scope = 'family' OR author_id = $8) AND ($5::text = 'family' OR author_id = $8)
RETURNING id, family_id, author_id, amount, date, category_id, type, scope, source, created_at, seller_inn, seller_name, receipt_key
`

type UpdateTransactionParams struct {
	Amount     int64     `json:"amount"`
	Date       time.Time `json:"date"`
	CategoryID string    `json:"categoryId"`
	Type       string    `json:"type"`
	Scope      string    `json:"scope"`
	ID         uuid.UUID `json:"id"`
	FamilyID   uuid.UUID `json:"familyId"`
	UserID     uuid.UUID `json:"userId"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.Amount,
		arg.Date,
		arg.CategoryID,
		arg.Type,
		arg.Scope,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AuthorID,
		&i.Amount,
		&i.Date,
		&i.CategoryID,
		&i.Type,
		&i.Scope,
		&i.Source,
		&i.CreatedAt,
		&i.SellerInn,
		&i.SellerName,
		&i.ReceiptKey,
	)
	return i, err
}
