// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID       string      `json:"id"`
	FamilyID pgtype.UUID `json:"familyId"`
	Name     string      `json:"name"`
	Kind     string      `json:"kind"`
}

type CategoryLimit struct {
	ID          uuid.UUID `json:"id"`
	FamilyID    uuid.UUID `json:"familyId"`
	UserID      uuid.UUID `json:"userId"`
	CategoryID  string    `json:"categoryId"`
	LimitAmount int64     `json:"limitAmount"`
	Scope       string    `json:"scope"`
}

type CreditCard struct {
	ID               uuid.UUID `json:"id"`
	FamilyID         uuid.UUID `json:"familyId"`
	UserID           uuid.UUID `json:"userId"`
	Bank             string    `json:"bank"`
	AmountDue        int64     `json:"amountDue"`
	DueDate          time.Time `json:"dueDate"`
	CategoryID       string    `json:"categoryId"`
	NotifyDaysBefore int32     `json:"notifyDaysBefore"`
	Scope            string    `json:"scope"`
	Status           string    `json:"status"`
	CreditLimit      *int64    `json:"creditLimit"`
	CreatedAt        time.Time `json:"createdAt"`
}

type Family struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}

type FamilyMember struct {
	UserID   uuid.UUID `json:"userId"`
	FamilyID uuid.UUID `json:"familyId"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joinedAt"`
}

type Invite struct {
	Code      string             `json:"code"`
	FamilyID  uuid.UUID          `json:"familyId"`
	CreatedBy uuid.UUID          `json:"createdBy"`
	ExpiresAt time.Time          `json:"expiresAt"`
	UsedAt    pgtype.Timestamptz `json:"usedAt"`
}

type RecurringPayment struct {
	ID               uuid.UUID  `json:"id"`
	FamilyID         uuid.UUID  `json:"familyId"`
	UserID           uuid.UUID  `json:"userId"`
	Name             string     `json:"name"`
	Kind             string     `json:"kind"`
	Amount           int64      `json:"amount"`
	Period           string     `json:"period"`
	NextDate         time.Time  `json:"nextDate"`
	CategoryID       string     `json:"categoryId"`
	NotifyDaysBefore int32      `json:"notifyDaysBefore"`
	Scope            string     `json:"scope"`
	Status           string     `json:"status"`
	TotalAmount      *int64     `json:"totalAmount"`
	EndDate          *time.Time `json:"endDate"`
	CreatedAt        time.Time  `json:"createdAt"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	TokenHash string    `json:"tokenHash"`
	ExpiresAt time.Time `json:"expiresAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type SavingsGoal struct {
	ID       uuid.UUID  `json:"id"`
	FamilyID uuid.UUID  `json:"familyId"`
	UserID   uuid.UUID  `json:"userId"`
	Name     string     `json:"name"`
	Target   *int64     `json:"target"`
	Saved    int64      `json:"saved"`
	Deadline *time.Time `json:"deadline"`
	Scope    string     `json:"scope"`
}

type Transaction struct {
	ID         uuid.UUID `json:"id"`
	FamilyID   uuid.UUID `json:"familyId"`
	AuthorID   uuid.UUID `json:"authorId"`
	Amount     int64     `json:"amount"`
	Date       time.Time `json:"date"`
	CategoryID string    `json:"categoryId"`
	Type       string    `json:"type"`
	Scope      string    `json:"scope"`
	Source     string    `json:"source"`
	CreatedAt  time.Time `json:"createdAt"`
	SellerInn  *string   `json:"sellerInn"`
	SellerName *string   `json:"sellerName"`
	ReceiptKey *string   `json:"receiptKey"`
}

type TransactionItem struct {
	ID            uuid.UUID `json:"id"`
	TransactionID uuid.UUID `json:"transactionId"`
	Position      int32     `json:"position"`
	Name          string    `json:"name"`
	Price         int64     `json:"price"`
	Quantity      float64   `json:"quantity"`
	Sum           int64     `json:"sum"`
	CategoryID    *string   `json:"categoryId"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"passwordHash"`
	Name         string    `json:"name"`
	Color        string    `json:"color"`
	CreatedAt    time.Time `json:"createdAt"`
}
