// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFamilyMember(ctx context.Context, arg AddFamilyMemberParams) error
	CloseCard(ctx context.Context, arg CloseCardParams) (int64, error)
	ClosePayment(ctx context.Context, arg ClosePaymentParams) (int64, error)
	ConsumeRefreshToken(ctx context.Context, tokenHash string) (uuid.UUID, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (CreditCard, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error)
	CreateFamily(ctx context.Context, name string) (Family, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (SavingsGoal, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreateLimit(ctx context.Context, arg CreateLimitParams) (CategoryLimit, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (RecurringPayment, error)
	CreateReceiptTransaction(ctx context.Context, arg CreateReceiptTransactionParams) (Transaction, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFamily(ctx context.Context, id uuid.UUID) error
	DeleteGoal(ctx context.Context, arg DeleteGoalParams) (int64, error)
	DeleteLimit(ctx context.Context, arg DeleteLimitParams) (int64, error)
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error)
	DeleteUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	GetActiveInvite(ctx context.Context, code string) (GetActiveInviteRow, error)
	GetCardForUpdate(ctx context.Context, arg GetCardForUpdateParams) (CreditCard, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error)
	GetFamily(ctx context.Context, id uuid.UUID) (Family, error)
	GetMembership(ctx context.Context, userID uuid.UUID) (FamilyMember, error)
	GetPaymentForUpdate(ctx context.Context, arg GetPaymentForUpdateParams) (RecurringPayment, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListCards(ctx context.Context, arg ListCardsParams) ([]CreditCard, error)
	ListCategories(ctx context.Context, familyID pgtype.UUID) ([]ListCategoriesRow, error)
	ListFamilyMembers(ctx context.Context, familyID uuid.UUID) ([]ListFamilyMembersRow, error)
	ListGoals(ctx context.Context, arg ListGoalsParams) ([]SavingsGoal, error)
	ListLimits(ctx context.Context, arg ListLimitsParams) ([]CategoryLimit, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]RecurringPayment, error)
	ListTransactionItems(ctx context.Context, arg ListTransactionItemsParams) ([]ListTransactionItemsRow, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	OldestMember(ctx context.Context, familyID uuid.UUID) (uuid.UUID, error)
	RemoveFamilyMember(ctx context.Context, arg RemoveFamilyMemberParams) (int64, error)
	SetCardDueDate(ctx context.Context, arg SetCardDueDateParams) error
	SetMemberRole(ctx context.Context, arg SetMemberRoleParams) error
	SetPaymentNextDate(ctx context.Context, arg SetPaymentNextDateParams) error
	TopUpGoal(ctx context.Context, arg TopUpGoalParams) (SavingsGoal, error)
	UpdateCard(ctx context.Context, arg UpdateCardParams) (CreditCard, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (SavingsGoal, error)
	UpdateLimit(ctx context.Context, arg UpdateLimitParams) (CategoryLimit, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (RecurringPayment, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UseInvite(ctx context.Context, code string) (int64, error)
}

var _ Querier = (*Queries)(nil)
