// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipt.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReceiptTransaction = `-- name: CreateReceiptTransaction :one
INSERT INTO transactions (family_id, author_id, amount, date, category_id, type, scope, source, seller_inn, seller_name, receipt_key)
VALUES ($1, $2, $3, $4, $5, 'expense', $6, 'receipt', $7, $8, $9)
RETURNING id, family_id, author_id, amount, date, category_id, type, scope, source, created_at, seller_inn, seller_name, receipt_key
`

type CreateReceiptTransactionParams struct {
	FamilyID   uuid.UUID `json:"familyId"`
	UserID     uuid.UUID `json:"userId"`
	Amount     int64     `json:"amount"`
	Date       time.Time `json:"date"`
	CategoryID string    `json:"categoryId"`
	Scope      string    `json:"scope"`
	SellerInn  *string   `json:"sellerInn"`
	SellerName *string   `json:"sellerName"`
	ReceiptKey *string   `json:"receiptKey"`
}

func (q *Queries) CreateReceiptTransaction(ctx context.Context, arg CreateReceiptTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createReceiptTransaction,
		arg.FamilyID,
		arg.UserID,
		arg.Amount,
		arg.Date,
		arg.CategoryID,
		arg.Scope,
		arg.SellerInn,
		arg.SellerName,
		arg.ReceiptKey,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AuthorID,
		&i.Amount,
		&i.Date,
		&i.CategoryID,
		&i.Type,
		&i.Scope,
		&i.Source,
		&i.CreatedAt,
		&i.SellerInn,
		&i.SellerName,
		&i.ReceiptKey,
	)
	return i, err
}

const createTransactionItem = `-- name: CreateTransactionItem :exec
INSERT INTO transaction_items (transaction_id, position, name, price, quantity, sum)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTransactionItemParams struct {
	TransactionID uuid.UUID `json:"transactionId"`
	Position      int32     `json:"position"`
	Name          string    `json:"name"`
	Price         int64     `json:"price"`
	Quantity      float64   `json:"quantity"`
	Sum           int64     `json:"sum"`
}

func (q *Queries) CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) error {
	_, err := q.db.Exec(ctx, createTransactionItem,
		arg.TransactionID,
		arg.Position,
		arg.Name,
		arg.Price,
		arg.Quantity,
		arg.Sum,
	)
	return err
}

const listTransactionItems = `-- name: ListTransactionItems :many
SELECT i.id, i.position, i.name, i.price, i.quantity, i.sum, i.category_id
FROM transaction_items i
JOIN transactions t ON t.id = i.transaction_id
WHERE i.transaction_id = $1 AND t.family_id = $2 AND (t.scope = 'family' OR t.author_id = $3)
ORDER BY i.position
`

type ListTransactionItemsParams struct {
	TransactionID uuid.UUID `json:"transactionId"`
	FamilyID      uuid.UUID `json:"familyId"`
	UserID        uuid.UUID `json:"userId"`
}

type ListTransactionItemsRow struct {
	ID         uuid.UUID `json:"id"`
	Position   int32     `json:"position"`
	Name       string    `json:"name"`
	Price      int64     `json:"price"`
	Quantity   float64   `json:"quantity"`
	Sum        int64     `json:"sum"`
	CategoryID *string   `json:"categoryId"`
}

func (q *Queries) ListTransactionItems(ctx context.Context, arg ListTransactionItemsParams) ([]ListTransactionItemsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionItems, arg.TransactionID, arg.FamilyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionItemsRow
	for rows.Next() {
		var i ListTransactionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Name,
			&i.Price,
			&i.Quantity,
			&i.Sum,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
